from policy_llm import rag_chain

# Define your query-context pairs here
pairs = [
    ("what is the return policy", "Refund Eligibility 1.Summary You may be eligible for a refund under the following conditions: 1.​ You have cancelled the order before dispatch. 2.​ You have returned the product in compliance with the Clothing Retail Return Policy, and the product has passed our quality verification check. Refunds are processed only for products purchased and paid for successfully, and not for COD orders that were refused at delivery. 2. Refund Process & Timeline Once your returned product reaches our warehouse: 1.​ The item undergoes verification and quality assessment. 2.​ Upon approval, the refund | Distance: 0.7651 Result 2: decision on the eligibility of a return, refund, or replacement is final and binding. Refund Eligibility 1.Summary You may be eligible for a refund under the following conditions: 1.​ You have cancelled the order before dispatch. 2.​ You have returned the product in compliance with the Clothing Retail Return Policy, and the product has passed our quality verification check. Refunds are processed only for products purchased and paid for successfully, and not for COD orders that were refused at delivery. 2. Refund Process & Timeline Once your returned product reaches our warehouse: 1.​ The item undergoes verification and quality assessment. 2.​ Upon approval, the refund | Distance: 0.7651"),
    ("can i get discount voucher if i return old clothes", "2.​ Sorting & Processing:​ ○​ Reusable items are donated or repurposed for second-hand resale. ○​ Recyclable fabrics are processed into new fibers and materials for production. ○​ Unusable textiles are converted into industrial materials (e.g., insulation, padding).​ 3.​ Reward:​ After each drop-off, the customer receives a digital or printed 15% discount voucher, redeemable on their next purchase. 4. Voucher Terms ●​ The voucher grants 15% off one new item of the customer’s choice. ●​ Valid for 30 days from issue date. ●​ Not combinable with other promotions or sales discounts. ●​ Limited to one voucher | Distance: 0.8315 Result 2: lection Boxes located near store entrances or customer service desks.​ 2.​ Sorting & Processing:​ ○​ Reusable items are donated or repurposed for second-hand resale. ○​ Recyclable fabrics are processed into new fibers and materials for production. ○​ Unusable textiles are converted into industrial materials (e.g., insulation, padding).​ 3.​ Reward:​ After each drop-off, the customer receives a digital or printed 15% discount voucher, redeemable on their next purchase. 4. Voucher Terms ●​ The voucher grants 15% off one new item of the customer’s choice. ●​ Valid for 30 days from issue date. ●​ Not combinable with other promotions or sales discounts. ●​ Limited to one voucher | Distance: 0.8315"),
    # Add more pairs up to 7 like:
    ("what are the payment policies avaialble", "Result 1: your orders using any of the following modes:1.​ Cash on Delivery (COD) – available at select PIN codes. 2.​ Credit Cards – all major Visa, MasterCard, Amex, and Rupay cards. 3.​ Debit Cards – all major domestic and international debit cards. 4.​ Net Banking – via leading Indian banks. 5.​ Digital Wallets – including Clothing Retail Wallet, PhonePe, PayTM, Amazon Pay, and others. 6.​ Gift Cards & Credits – redeemed through the Clothing Retail Wallet. ⚠️ Payment methods available at checkout may vary depending on your location and product category.  2. Cash on Delivery (COD) How it works: ●​With COD, you can pay in cash at the time of delivery. ●​COD is available for orders va | Distance: 0.7570Result 2: your orders using any of the following modes: 1.​ Cash on Delivery (COD) – available at select PIN codes. 2.​ Credit Cards – all major Visa, MasterCard, Amex, and Rupay cards. 3.​ Debit Cards – all major domestic and international debit cards. 4.​ Net Banking – via leading Indian banks. 5.​ Digital Wallets – including Clothing Retail Wallet, PhonePe, PayTM, Amazon Pay, and others. 6.​ Gift Cards & Credits – redeemed through the Clothing Retail Wallet.⚠️ Payment methods available at checkout may vary depending on your location and product category.  2. Cash on Delivery (COD) How it works: With COD, you can pay in cash at the time of delivery. COD is available for orders va | Distance: 0.7570"),
    ("what is the refund conditions?", "Refund Eligibility 1.Summary You may be eligible for a refund under the following conditions: 1.​ You have cancelled the order before dispatch. 2.​ You have returned the product in compliance with the Clothing Retail Return Policy, and the product has passed our quality verification check. Refunds are processed only for products purchased and paid for successfully, and not for COD orders that were refused at delivery. 2. Refund Process & Timeline Once your returned product reaches our warehouse: 1.​ The item undergoes verification and quality assessment. 2.​ Upon approval, the refund | Distance: 0.7276 Result 2: decision on the eligibility of a return, refund, or replacement is final and binding. Refund Eligibility 1.Summary You may be eligible for a refund under the following conditions: 1.​ You have cancelled the order before dispatch. 2.​ You have returned the product in compliance with the Clothing Retail Return Policy, and the product has passed our quality verification check. Refunds are processed only for products purchased and paid for successfully, and not for COD orders that were refused at delivery. 2. Refund Process & Timeline Once your returned product reaches our warehouse: 1.​ The item undergoes verification and quality assessment. 2.​ Upon approval, the refund | Distance: 0.7276"),
    ("how is the shipping done?","Result 1: 6. Partial or Missing Deliveries If you receive: ●​ A partial delivery (missing items), or ●​ A tampered/empty package, Please contact our support team within 72 hours of delivery to raise an investigation. During the investigation: 1.​ Do not use or dispose of the product or packaging. 2.​ Provide clear images of: o​ The received package and its labels. o​ Any tampered or damaged sides. 3.​ Keep the invoice and packaging for at least 4 days post-delivery as our logistics team may require it for verification. 4.​ Refunds or exchanges for missing items will be processed only after investigation confirmation. Failure to provide sufficient details or images may lead to claim re | Distance: 1.0964 Result 2: 6. Partial or Missing Deliveries If you receive: ●​ A partial delivery (missing items), or ●​ A tampered/empty package, Please contact our support team within 72 hours of delivery to raise an investigation. During the investigation: 1.​ Do not use or dispose of the product or packaging. 2.​ Provide clear images of: o​ The received package and its labels. o​ Any tampered or damaged sides. 3.​ Keep the invoice and packaging for at least 4 days post-delivery as our logistics team may require it for verification. 4.​ Refunds or exchanges for missing items will be processed only after investigation confirmation. Failure to provide sufficient details or images may lead to claim re | Distance: 1.0964")
]

# Open a single text file to store all responses
with open("rag_responses-all-MiniLM.txt", "w") as file:
    for i, (query, context) in enumerate(pairs, start=1):
        response = rag_chain.invoke({
            "history": "",
            "context": context,
            "query": query
        })

        file.write(f"--- Query {i} ---\n")
        file.write(f"Query: {query}\n")
        file.write(f"Context: {context}\n")
        file.write(f"Response: {response}\n\n")

print("✅ All query-response pairs saved to rag_responses.txt")